---
- name: Creating Ubuntu instance
  hosts: localhost
  connection: local
  vars_files:
    - variable.vars
  tasks:
    - name: Ec2 creation
      ec2:
        region: "us-east-1"
        instance_type: t2.micro
        key_name: project
        image: "ami-0885b1f6bd170450c"
        vpc_subnet_id: "subnet-3211fd13"
        assign_public_ip: yes
        instance_tags:
          Name: Ansible-Ubuntu
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
      register: ec2_data
    
    - name: EC2 Details
      ec2_instance_facts:
        region: "us-east-1"
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        instance_ids: "{{ ec2_data.instances[0].id }}"
      register: ec2_metadata

    - name: Create inventory group
      add_host:   
        groupname: Ubuntuec2
        hostname: "{{ec2_metadata.instances[0].public_ip_address}}"
        ansible_user: ubuntu
        ansible_ssh_private_key_file: project.pem
    
    - name: Wait for SSH to come up
      wait_for: 
        host: "{{ec2_metadata.instances[0].public_ip_address}}"
        port: 22 
        state: started
    
- hosts: Ubuntuec2
  become: true
  vars_files:
    - variable.vars
  tasks:
    - name: Waiting...
      pause:
        prompt: Waiting for 60 seconds...
        seconds: 60

    - name: Updating apt-get
      shell: apt-get update -y
      args:
        warn: false

    - name: Install required system packages
      apt: 
        name: "{{ item }}"
        state: latest 
        update_cache: yes
      with_items: 
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
        - unzip

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        update_cache: yes 
        name: docker-ce
        state: latest

    - name: Installing Docker Module for Python
      pip:
        name: docker
    
    - name: Adding ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
    
    - name: Pull latest Wordpress and Mysql images
      docker_image:
        name: "{{ item }}"
        source: pull
      with_items:
        - "{{ wordpress_image }}"
        - "{{ mysql_image }}"

    - name: Create Docker volume
      docker_volume:
        name: wpdata

    - name: Copying env files
      copy:
        src: "{{ item }}"
        dest: /home/ubuntu/
      with_items:
        - wordpress.env
        - mysql.env

    - name: Creating a nework for Wordpress and MySQL
      docker_network:
        name: wpdb

    - name: Creating Wordpress container
      docker_container:
        name: "{{ wordpress_name }}"
        image: "{{ wordpress_image }}"
        state: started
        networks:
          - name: wpdb
        ports:
          - "80:80"
        volumes:
          - wpdata:/usr/local/apache2/htdocs/
        restart: yes
        restart_policy: unless-stopped
        env_file: /home/ubuntu/wordpress.env

    - name: Creating Mysql container
      docker_container:
        name: "{{ mysql_name }}"
        image: "{{ mysql_image }}"
        state: started
        networks:
          - name: wpdb
        restart: yes
        restart_policy: unless-stopped
        env_file: /home/ubuntu/mysql.env

